// Single source of truth for the public catalogue.
// Mirrors supabase/migrations/20260916010000_videos_admin.sql seed;
// used as the SSR/static fallback when the live DB is unreachable.
export type Aspect = "landscape" | "portrait" | "4x5";
export type Platform = "instagram" | "youtube" | "vimeo";
export interface Video {
  section: string;
  sub: string | null;
  platform: Platform;
  code: string;
  kind: string;
  aspect: Aspect;
  title: string;
  detail: string;
  thumb: string;
  link: string;
  featured: boolean;
  position: number;
  file_path?: string | null;
}
export const VIDEOS: Video[] = [
  {
    section: "start",
    sub: null,
    platform: "instagram",
    code: "DcOVIS-hYFM",
    kind: "p",
    aspect: "landscape",
    title: "Brand episode EP.01",
    detail: "documentary cafe cut with interview audio",
    thumb: "/assets/thumbs/start-0.webp",
    link: "https://www.instagram.com/p/DcOVIS-hYFM/",
    featured: true,
    position: 0,
  },
  {
    section: "start",
    sub: "Teaser",
    platform: "youtube",
    code: "FiM8u5WwFqY",
    kind: "watch",
    aspect: "portrait",
    title: "Wedding teaser",
    detail: "cinematic day cut, vows over highlights",
    thumb: "/assets/thumbs/start-1.webp",
    link: "https://youtu.be/FiM8u5WwFqY",
    featured: true,
    position: 1,
  },
  {
    section: "start",
    sub: null,
    platform: "youtube",
    code: "Xs7fZwrrm1k",
    kind: "shorts",
    aspect: "portrait",
    title: "Podcast reel",
    detail: "hook-first cutdown, burned captions, punch-ins",
    thumb: "/assets/thumbs/start-2.webp",
    link: "https://youtube.com/shorts/Xs7fZwrrm1k?feature=share",
    featured: true,
    position: 2,
  },
  {
    section: "start",
    sub: null,
    platform: "instagram",
    code: "DcByFKtKArh",
    kind: "p",
    aspect: "4x5",
    title: "Travel reel",
    detail: "24-hour city cut with whip-pan transitions",
    thumb: "/assets/thumbs/start-3.webp",
    link: "https://www.instagram.com/p/DcByFKtKArh/",
    featured: true,
    position: 3,
  },
  {
    section: "start",
    sub: null,
    platform: "youtube",
    code: "93ae6RAZvyk",
    kind: "watch",
    aspect: "landscape",
    title: "Music video",
    detail: "performance cover cut on lyric rhythm, film grade",
    thumb: "/assets/thumbs/start-4.webp",
    link: "https://youtu.be/93ae6RAZvyk",
    featured: true,
    position: 4,
  },
  {
    section: "start",
    sub: null,
    platform: "youtube",
    code: "Htwl7paWltc",
    kind: "shorts",
    aspect: "portrait",
    title: "Event recap",
    detail: "library launch session cut with ambient audio",
    thumb: "/assets/thumbs/start-5.webp",
    link: "https://youtube.com/shorts/Htwl7paWltc?feature=share",
    featured: true,
    position: 5,
  },
  {
    section: "brands",
    sub: null,
    platform: "instagram",
    code: "DVLtg40GFvd",
    kind: "p",
    aspect: "landscape",
    title: "Cafe brand reel",
    detail: "ambient slow cut with on-screen type",
    thumb: "/assets/thumbs/00.webp",
    link: "https://www.instagram.com/p/DVLtg40GFvd/",
    featured: false,
    position: 6,
  },
  {
    section: "brands",
    sub: null,
    platform: "youtube",
    code: "AyzYq_UUWw4",
    kind: "shorts",
    aspect: "portrait",
    title: "BTS reel",
    detail: "behind-the-scenes selects cut on beat for launch",
    thumb: "/assets/thumbs/01.webp",
    link: "https://youtube.com/shorts/AyzYq_UUWw4?feature=share",
    featured: false,
    position: 7,
  },
  {
    section: "brands",
    sub: null,
    platform: "instagram",
    code: "DPG2_8CCVIR",
    kind: "p",
    aspect: "landscape",
    title: "Campaign film",
    detail: "product-led cut, motion type, clean grade",
    thumb: "/assets/thumbs/02.webp",
    link: "https://www.instagram.com/p/DPG2_8CCVIR/",
    featured: false,
    position: 8,
  },
  {
    section: "brands",
    sub: null,
    platform: "vimeo",
    code: "809772240",
    kind: "video",
    aspect: "landscape",
    title: "Fashion concept film",
    detail: "AW22 lookbook cut on rhythm",
    thumb: "/assets/thumbs/03.webp",
    link: "https://vimeo.com/809772240?share=copy&fl=sv&fe=ci",
    featured: false,
    position: 9,
  },
  {
    section: "brands",
    sub: null,
    platform: "instagram",
    code: "DMvIfFbv899",
    kind: "p",
    aspect: "landscape",
    title: "Product reveal",
    detail: "candlelit pack launch, macro detail, warm grade",
    thumb: "/assets/thumbs/04.webp",
    link: "https://www.instagram.com/p/DMvIfFbv899/",
    featured: false,
    position: 10,
  },
  {
    section: "brands",
    sub: null,
    platform: "instagram",
    code: "DQoo446k1Sa",
    kind: "p",
    aspect: "landscape",
    title: "Brand mood reel",
    detail: "low-light ambience edit on texture and pace",
    thumb: "/assets/thumbs/05.webp",
    link: "https://www.instagram.com/p/DQoo446k1Sa/",
    featured: false,
    position: 11,
  },
  {
    section: "brands",
    sub: null,
    platform: "vimeo",
    code: "1089372399",
    kind: "video",
    aspect: "landscape",
    title: "Brand event recap",
    detail: "book-fair coverage cut to a tight promo",
    thumb: "/assets/thumbs/06.webp",
    link: "https://vimeo.com/1089372399?share=copy",
    featured: false,
    position: 12,
  },
  {
    section: "brands",
    sub: null,
    platform: "instagram",
    code: "DcOVIS-hYFM",
    kind: "p",
    aspect: "landscape",
    title: "Brand episode EP.01",
    detail: "documentary cafe cut with interview audio",
    thumb: "/assets/thumbs/07.webp",
    link: "https://www.instagram.com/p/DcOVIS-hYFM/",
    featured: false,
    position: 13,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "instagram",
    code: "DTCw5o8EuTo",
    kind: "p",
    aspect: "landscape",
    title: "Wedding teaser",
    detail: "interview-led story, multi-day footage to 60s",
    thumb: "/assets/thumbs/08.webp",
    link: "https://www.instagram.com/p/DTCw5o8EuTo/",
    featured: false,
    position: 14,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "youtube",
    code: "FiM8u5WwFqY",
    kind: "watch",
    aspect: "portrait",
    title: "Wedding teaser",
    detail: "cinematic day cut, vows over highlights",
    thumb: "/assets/thumbs/09.webp",
    link: "https://youtu.be/FiM8u5WwFqY",
    featured: false,
    position: 15,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "youtube",
    code: "n00jKOWNkWA",
    kind: "watch",
    aspect: "landscape",
    title: "Wedding teaser",
    detail: "same-day edit cut for social release",
    thumb: "/assets/thumbs/10.webp",
    link: "https://youtu.be/n00jKOWNkWA",
    featured: false,
    position: 16,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "youtube",
    code: "0aE-UoaBM1M",
    kind: "watch",
    aspect: "landscape",
    title: "Wedding teaser",
    detail: "ritual-focused cut on traditional music bed",
    thumb: "/assets/thumbs/11.webp",
    link: "https://youtu.be/0aE-UoaBM1M",
    featured: false,
    position: 17,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "youtube",
    code: "psdmUGWJIKs",
    kind: "watch",
    aspect: "landscape",
    title: "Wedding teaser",
    detail: "emotion-first build, slow ramps into the drop",
    thumb: "/assets/thumbs/12.webp",
    link: "https://youtu.be/psdmUGWJIKs",
    featured: false,
    position: 18,
  },
  {
    section: "weddings",
    sub: "Teaser",
    platform: "vimeo",
    code: "809883854",
    kind: "video",
    aspect: "landscape",
    title: "Wedding teaser",
    detail: "cinematic grade with an audio-driven build",
    thumb: "/assets/thumbs/13.webp",
    link: "https://vimeo.com/809883854?share=copy#t=0",
    featured: false,
    position: 19,
  },
  {
    section: "weddings",
    sub: "Highlight",
    platform: "youtube",
    code: "bhu-BE4t27Y",
    kind: "watch",
    aspect: "landscape",
    title: "Wedding highlight",
    detail: "4-min film from two-day multi-cam coverage",
    thumb: "/assets/thumbs/14.webp",
    link: "https://youtu.be/bhu-BE4t27Y",
    featured: false,
    position: 20,
  },
  {
    section: "weddings",
    sub: "Highlight",
    platform: "vimeo",
    code: "1089374583",
    kind: "video",
    aspect: "landscape",
    title: "Bride highlight",
    detail: "haldi detail cut, macro sequencing, soft grade",
    thumb: "/assets/thumbs/15.webp",
    link: "https://vimeo.com/1089374583?share=copy#t=0",
    featured: false,
    position: 21,
  },
  {
    section: "weddings",
    sub: "Reel",
    platform: "youtube",
    code: "cNddJLrKFwE",
    kind: "shorts",
    aspect: "portrait",
    title: "Vertical wedding reel",
    detail: "getting-ready moments cut to trend audio",
    thumb: "/assets/thumbs/16.webp",
    link: "https://youtube.com/shorts/cNddJLrKFwE?feature=share",
    featured: false,
    position: 22,
  },
  {
    section: "weddings",
    sub: "Reel",
    platform: "youtube",
    code: "94j_jG4AWZc",
    kind: "shorts",
    aspect: "portrait",
    title: "Vertical wedding reel",
    detail: "couple portrait cut with speed ramps",
    thumb: "/assets/thumbs/17.webp",
    link: "https://youtube.com/shorts/94j_jG4AWZc?feature=share",
    featured: false,
    position: 23,
  },
  {
    section: "weddings",
    sub: "Reel",
    platform: "youtube",
    code: "PGf1mhYZWDM",
    kind: "shorts",
    aspect: "portrait",
    title: "Vertical barat reel",
    detail: "high-energy procession cut on beat",
    thumb: "/assets/thumbs/18.webp",
    link: "https://youtube.com/shorts/PGf1mhYZWDM?feature=share",
    featured: false,
    position: 24,
  },
  {
    section: "events",
    sub: null,
    platform: "youtube",
    code: "Htwl7paWltc",
    kind: "shorts",
    aspect: "portrait",
    title: "Event recap",
    detail: "library launch session cut with ambient audio",
    thumb: "/assets/thumbs/19.webp",
    link: "https://youtube.com/shorts/Htwl7paWltc?feature=share",
    featured: false,
    position: 25,
  },
  {
    section: "events",
    sub: null,
    platform: "instagram",
    code: "DRj5MJdE5t2",
    kind: "p",
    aspect: "landscape",
    title: "Event aftermovie",
    detail: "community meetup recap, multi-angle cut",
    thumb: "/assets/thumbs/20.webp",
    link: "https://www.instagram.com/p/DRj5MJdE5t2/",
    featured: false,
    position: 26,
  },
  {
    section: "events",
    sub: null,
    platform: "instagram",
    code: "DSsTsZSk0Sq",
    kind: "p",
    aspect: "landscape",
    title: "Event promo",
    detail: "two-day board-game expo cut into a hype reel",
    thumb: "",
    link: "https://www.instagram.com/p/DSsTsZSk0Sq/",
    featured: false,
    position: 27,
  },
  {
    section: "podcasts",
    sub: null,
    platform: "youtube",
    code: "wVYEAjI7mcI",
    kind: "shorts",
    aspect: "portrait",
    title: "Podcast cutdown",
    detail: "long-form to vertical with animated captions",
    thumb: "/assets/thumbs/22.webp",
    link: "https://youtube.com/shorts/wVYEAjI7mcI?feature=share",
    featured: false,
    position: 28,
  },
  {
    section: "podcasts",
    sub: null,
    platform: "youtube",
    code: "LOZOXXrs_Cg",
    kind: "watch",
    aspect: "landscape",
    title: "Podcast edit",
    detail: "multi-cam sync, audio clean-up, caption pass",
    thumb: "/assets/thumbs/23.webp",
    link: "https://youtu.be/LOZOXXrs_Cg",
    featured: false,
    position: 29,
  },
  {
    section: "podcasts",
    sub: null,
    platform: "instagram",
    code: "DPf0YuzCEeA",
    kind: "p",
    aspect: "landscape",
    title: "Podcast promo",
    detail: "studio session cutdown with kinetic type",
    thumb: "/assets/thumbs/24.webp",
    link: "https://www.instagram.com/p/DPf0YuzCEeA/",
    featured: false,
    position: 30,
  },
  {
    section: "podcasts",
    sub: null,
    platform: "youtube",
    code: "Xs7fZwrrm1k",
    kind: "shorts",
    aspect: "portrait",
    title: "Podcast reel",
    detail: "hook-first cutdown, burned captions, punch-ins",
    thumb: "/assets/thumbs/25.webp",
    link: "https://youtube.com/shorts/Xs7fZwrrm1k?feature=share",
    featured: false,
    position: 31,
  },
  {
    section: "podcasts",
    sub: null,
    platform: "youtube",
    code: "nZXvBY1rPkE",
    kind: "shorts",
    aspect: "portrait",
    title: "Podcast reel",
    detail: "argument-beat cutdown with subtitle emphasis",
    thumb: "/assets/thumbs/26.webp",
    link: "https://youtube.com/shorts/nZXvBY1rPkE?feature=share",
    featured: false,
    position: 32,
  },
  {
    section: "travel",
    sub: null,
    platform: "instagram",
    code: "DcByFKtKArh",
    kind: "p",
    aspect: "4x5",
    title: "Travel reel",
    detail: "24-hour city cut with whip-pan transitions",
    thumb: "/assets/thumbs/27.webp",
    link: "https://www.instagram.com/p/DcByFKtKArh/",
    featured: false,
    position: 33,
  },
  {
    section: "travel",
    sub: null,
    platform: "instagram",
    code: "DW1kfT2AMe8",
    kind: "p",
    aspect: "landscape",
    title: "Travel film",
    detail: "Kyoto slow-travel cut, season-matched grade",
    thumb: "/assets/thumbs/28.webp",
    link: "https://www.instagram.com/p/DW1kfT2AMe8/",
    featured: false,
    position: 34,
  },
  {
    section: "travel",
    sub: null,
    platform: "instagram",
    code: "DV8iK0yAOjB",
    kind: "reel",
    aspect: "landscape",
    title: "Creator reel",
    detail: "vertical travel moment cut to trending audio",
    thumb: "/assets/thumbs/29.webp",
    link: "https://www.instagram.com/reel/DV8iK0yAOjB/",
    featured: false,
    position: 35,
  },
  {
    section: "travel",
    sub: null,
    platform: "vimeo",
    code: "1098982278",
    kind: "video",
    aspect: "landscape",
    title: "Trek film",
    detail: "Himalayan trek doc cut from handheld footage",
    thumb: "/assets/thumbs/30.webp",
    link: "https://vimeo.com/1098982278?share=copy",
    featured: false,
    position: 36,
  },
  {
    section: "travel",
    sub: null,
    platform: "instagram",
    code: "DU8Y-9AD-RC",
    kind: "p",
    aspect: "landscape",
    title: "Festival travel reel",
    detail: "mountain festival story, native audio",
    thumb: "/assets/thumbs/31.webp",
    link: "https://www.instagram.com/p/DU8Y-9AD-RC/",
    featured: false,
    position: 37,
  },
  {
    section: "music",
    sub: null,
    platform: "youtube",
    code: "93ae6RAZvyk",
    kind: "watch",
    aspect: "landscape",
    title: "Music video",
    detail: "performance cover cut on lyric rhythm, film grade",
    thumb: "/assets/thumbs/32.webp",
    link: "https://youtu.be/93ae6RAZvyk",
    featured: false,
    position: 38,
  },
  {
    section: "music",
    sub: null,
    platform: "youtube",
    code: "Hv52-OHDL_k",
    kind: "watch",
    aspect: "landscape",
    title: "Music video",
    detail: "narrative cover edit synced to vocal phrasing",
    thumb: "/assets/thumbs/33.webp",
    link: "https://youtu.be/Hv52-OHDL_k",
    featured: false,
    position: 39,
  },
];

export interface SectionMeta {
  id: string;
  label: string;
  subs?: string[];
}
export const SECTIONS: SectionMeta[] = [
  { id: "travel", label: "Travel" },
  { id: "brands", label: "Brands" },
  { id: "weddings", label: "Weddings", subs: ["Teaser", "Highlight", "Reel"] },
  { id: "events", label: "Events" },
  { id: "podcasts", label: "Podcasts" },
  { id: "music", label: "Music" },
];

export const CONTACT = {
  whatsapp:
    "https://api.whatsapp.com/send?phone=919997100445&text=" +
    encodeURIComponent("Hi V-EDT — I have a project in mind:"),
  phoneDisplay: "+91 99971 00445",
  phoneTel: "tel:+919997100445",
  email: "v.edt.house@gmail.com",
};
